### ISSUE TITLE
warning: failed to load external entity "schemas/*/xml_schema_flat/*"

### ISSUE THREAD

**Issue by MihailCosmin** [kibook/vim-s1000d-omnicomplete#1]
Trying to build this on Linux Mint, and I get this error message:

> Converting schemas/ * /xml_schema_flat/* to vim/autoload/xml/*_*.vim...
> warning: failed to load external entity "schemas/ * /xml_schema_flat/*"
> unable to parse schemas/ * /xml_schema_flat/*
> -:1: parser error : Document is empty
> 
> ^
> unable to parse -

**Comment by kibook** [comment]
If you are just looking to use these dictionaries, the repo comes with them pre-built. Simply copy the contents of the "vim" directory to your ~/.vim directory.

As for why it's not building, you need to place the S1000D XML schemas you want to convert to Vim Omnicomplete dictionaries in a "schemas" directory, e.g. "schemas/S1000D_4-1/xml_schema_flat/descript.xsd".

Let me know if that solves your issue, or if you're still having trouble installing these. In the meantime, I will work on getting some proper instructions for installing and building in the README!

**Comment by MihailCosmin** [comment]
I copied the contents of the "vim" directory in both etc/vim/ and home/username/.vim
but nothing really happens in Vim while editing a DM.
Is there someway I should trigger the auto-complete suggestion 'menu'?

**Comment by kibook** [comment]
To activate Omnicomplete, do Ctrl-X Ctrl-O. For an element, type the opening < first, then Ctrl-X Ctrl-O.

**Comment by kibook** [comment]
You can also use a Vim plugin such as [AutoComplPop](https://www.vim.org/scripts/script.php?script_id=1879) to have the auto-complete suggestions appear automatically as you type.

**Comment by kibook** [comment]
You may need to follow this to enable the Vim filetype plugin/Omnicomplete as well: https://vim.fandom.com/wiki/Omni_completion

Vim has some dictionaries for more common XML schemas built-in (such as XHTML), so you can determine if Omnicomplete is working by doing:
```
:XMLns xhtml11
```
That will set the default XML namespace (elements without a namespace prefix) to XHTML. Then try auto-completing some XHTML elements. If that works, all you need to do to activate these S1000D dictionaries instead is:
```
:XMLns S1000D_50_descript
```
(in this case, that loads the S1000D Issue 5.0 Descriptive DM schema)

The last component of this plugin is the ftdetect script, which determines the appropriate schema based on the noNamespaceSchemaLocation URL, so that you don't have to type the :XMLns command manually each time you open a DM. This won't be active unless you have something like `filetype plugin on` in your .vimrc

**Comment by MihailCosmin** [comment]
Thanks, now it works, took some time to set things up, but now it works.

**Comment by kibook** [comment]
Great! I'm glad you got it working. I updated the README so that, hopefully, it's more clear how to get started in future.
